# -*- coding: utf-8 -*-
"""ML_Prac_09

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mMFomP_eQnNfD17dPR10Qav0RJfv7VRl
"""

import numpy as np

tensor_id = np.array([1.3, 1, 4.0, 23.99])

print(tensor_id)

print(tensor_id[0])

print(tensor_id[2])

import numpy as np

tensor_2d = np.array([(1, 2, 3, 4), (4, 5, 6, 7), (8, 9, 10, 11), (12, 13, 14, 15)])

print(tensor_2d)

tensor_2d[3] [2]

"""**TENSOR HANDLING AND MANIPULATION**"""

import tensorflow as tf
import numpy as np


matrix1 = np.array([(2, 2, 2), (2, 2, 2), (2, 2, 2)], dtype = 'int32')
matrix2 = np.array([(1, 1, 1), (1, 1, 1), (1, 1, 1)], dtype = 'int32')

print(matrix1)

matrix1 = tf.constant(matrix1)
matrix2 = tf.constant(matrix2)
matrix_product = tf.matmul(matrix1, matrix2)
matrix_sum = tf.add(matrix1, matrix2)
matrix_sub = tf.subtract(matrix1, matrix2)
matrix_div = tf.divide(matrix1, matrix2)
matrix_3 = np.array([(2, 7, 2), (1, 4, 2), (9, 0, 2)], dtype = 'float32')
print(matrix_3)
print(matrix_product)
print(matrix_sum)
print(matrix_sub)
print(matrix_div)

import tensorflow as tf
a = tf.constant([7, 8, 13, 11], dtype = tf.float64)
b = tf.constant([2, 13, 14, 5], dtype = tf.float64)

print('a:', a)
print('b:', b)

res = tf.math.less(x = a, y = b)

print('Result:', res)
