# -*- coding: utf-8 -*-
"""ML_Prac_01

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pqCKCF_aAwFczRCGI2nx0-b18JPSSeVe
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

dataset=pd.read_csv("/content/Salary_Data.csv")
x=dataset.iloc[:, :-1].values
y=dataset.iloc[:, -1].values

print(x)

print(y)

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=1/3, random_state=0)

print(x_train)

print(y_train)

print(x_test)

print(y_test)

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train, y_train)

y_pred = regressor.predict(x_test)

plt.scatter(x_train, y_train,color='red')
plt.plot(x_train,regressor.predict(x_train),color='blue')
plt.title('Salary vs Experience (Training set)')
plt.xlabel ('Year of Experiene')
plt.ylabel ('Salary')
plt.show()