# -*- coding: utf-8 -*-
"""ML_Prac_04

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OgFMlbBaY11TKATCFojWb2C7ChpjcKUm
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

dataset = pd.read_csv("Social_Network_Ads.csv")
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

from sklearn.model_selection import train_test_split
x_train, x_test ,y_train, y_test = train_test_split(x,y, test_size=0.25, random_state=0)

print(x_train)

print(x_test)

print(y_train)

print(y_test)

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test =sc.transform(x_test)

print(x_train)

print(x_test)

from sklearn.svm import SVC
classifier =SVC(kernel="linear" ,random_state=0)
classifier.fit(x_train,y_train)

print(classifier.predict(sc.transform([[30,200000]])))

y_pred = classifier.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)